=== staunchCloud/xmlProcessor/tempWorkingSpace/Demo/SchemaTest/shipOrder.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="orderPerson" type="xs:string"/>

	<xs:element name="name" type="xs:string"/>
	<xs:element name="address" type="xs:string"/>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="country" type="xs:string"/>

	<xs:element name="title" type="xs:string"/>
	<xs:element name="note" type="xs:string"/>
	<xs:element name="quantity" type="xs:integer"/>
	<xs:element name="price">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:totalDigits value="5"/>
				<xs:fractionDigits value="2" fixed="true"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>		

	<xs:attribute name="orderID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>


	<xs:element name="shipTo">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="address"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
			<xs:attribute name="shipDate" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="note" minOccurs="0"/>
				<xs:element ref="quantity"/>
				<xs:element ref="price"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:element name="shipOrder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="orderPerson"/>
				<xs:element ref="shipTo"/>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="orderID" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== staunchCloud/xmlProcessor/static/tempWorkingSpace/show/SchemaTest/shipOrderFail.xml
<?xml version="1.0"?>


<shipOrder orderID="889923"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!--xsi:noNamespaceSchemaLocation="shipOrder.xsd"-->
	<orderPerson>George Bush</orderPerson>
	<shipTo> <!--can have attribute or not since it does not use 'use="required"'-->
		<name>John Adams</name>
		<address>Oxford Street</address>
		<city>London</city>
		<country>UK</country>
		additional information
	</shipTo>
	<item>
		<price>10312.00</price>
		<title>Empire Burlesque</title>
		<note>Special Edition</note>
		<quantity>1</quantity>

	</item>
	<item>
		<title>Hide your heart</title>
		<quantity>1</quantity>
		<price>9.0000000000000000</price>
	</item>

</shipOrder>

=== staunchCloud/xmlProcessor/bin/src/main/resources/shipOrder.xml
<?xml version="1.0" encoding="UTF-8"?>

<shipOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" orderID="889923">  
  <!--xsi:noNamespaceSchemaLocation="shipOrder.xsd"-->  
  <orderPerson ID="1">George Bush</orderPerson>  
  <shipTo id="1" ID="2"> 
    <!--can have attribute or not since it does not use 'use="required"'-->  
    <name>John Adams</name>  
    <address>Oxford Street</address>  
    <city>London</city>  
    <country>UK</country> additional information
  </shipTo>  
  <item id233="2" ID="3"> 
    <title>Empire Burlesque</title>  
    <note>Special Edition</note>  
    <quantity>1</quantity>  
    <price>10312.00</price> 
  </item>  
  <item maxiya="3" ID="4"> 
    <title>Hide your heart</title>  
    <quantity>1</quantity>  
    <price>9.0000000000000000</price> 
  </item>  
  <tahahahhaahhaha ID="5"/>  
  <it23498576 ID="6"/> 
</shipOrder>
